CREATE TABLE IF NOT EXISTS VENDAS(
    id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    produto       VARCHAR2(100) NOT NULL,
    categoria     VARCHAR2(50)  NOT NULL,
    valor         NUMBER(10,2)  NOT NULL CHECK (valor > 0),
    data_venda    DATE          DEFAULT SYSDATE,
    vendedor      VARCHAR2(100) NOT NULL
);

INSERT INTO VENDAS (produto, categoria, valor, data_venda, vendedor) 
VALUES 
    ('Notebook Dell', 'Eletrônicos', 4500.00, DATE '2025-04-01', 'Carlos'),
    ('Mouse Gamer', 'Acessórios', 150.00, DATE '2025-04-01', 'Ana'),
    ('Teclado Mecânico', 'Acessórios', 300.00, DATE '2025-04-02', 'Carlos'),
    ('Monitor 24"', 'Eletrônicos', 1200.00, DATE '2025-04-02', 'Bruna'),
    ('Fone Bluetooth', 'Acessórios', 200.00, DATE '2025-04-03', 'Ana'),
    ('Notebook HP', 'Eletrônicos', 4000.00, DATE '2025-04-03', 'Carlos'),
    ('Webcam HD', 'Acessórios', 180.00, DATE '2025-04-04', 'Bruna'),
    ('Carregador Portátil', 'Acessórios', 120.00, DATE '2025-04-04', 'Ana'),
    ('SSD 1TB', 'Componentes', 500.00, DATE '2025-04-05', 'Carlos'),
    ('Cabo HDMI', 'Acessórios', 50.00, DATE '2025-04-05', 'Bruna');

DROP TABLE CLIENTES;
CREATE TABLE IF NOT EXISTS CLIENTES (
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    NOME VARCHAR(100),
    CIDADE VARCHAR(50),
    ESTADO VARCHAR(2)

);

INSERT INTO CLIENTES(NOME,CIDADE,ESTADO) VALUES
('Maddie', 'São Paulo', 'SP'),
('Felipe', 'Macapá', 'AP'),
('Samuel', 'Porto Velho', 'RO');

ALTER TABLE VENDAS ADD ID_CLIENTE NUMBER;
ALTER TABLE VENDAS ADD CONSTRAINT FK_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID);

UPDATE VENDAS
SET ID_CLIENTE = CASE VENDEDOR
    WHEN 'Carlos' THEN 1
    WHEN 'Ana' THEN 2
    WHEN 'Bruna' THEN 3
END;

SELECT PRODUTO, ID_CLIENTE FROM VENDAS;


-- Liste o nome do cliente e o produto de cada venda, mostrando também a cidade.
SELECT
    v.produto,
    c.nome AS cliente,
    c.cidade
FROM VENDAS v
INNER JOIN CLIENTES c
    ON v.id_cliente = c.id;

select * from clientes;
select * from vendas;

-- Mostre o total de vendas por estado.
SELECT
    COUNT(v.DATA_VENDA) AS QTD_VENDAS,
    c.ESTADO
FROM VENDAS v
INNER JOIN CLIENTES c
    ON c.id = v.id_cliente
GROUP BY c.ESTADO;

-- CREATE TABLE IF NOT EXISTS VENDAS(
    id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    produto       VARCHAR2(100) NOT NULL,
    categoria     VARCHAR2(50)  NOT NULL,
    valor         NUMBER(10,2)  NOT NULL CHECK (valor > 0),
    data_venda    DATE          DEFAULT SYSDATE,
    vendedor      VARCHAR2(100) NOT NULL
);

INSERT INTO VENDAS (produto, categoria, valor, data_venda, vendedor) 
VALUES 
    ('Notebook Dell', 'Eletrônicos', 4500.00, DATE '2025-04-01', 'Carlos'),
    ('Mouse Gamer', 'Acessórios', 150.00, DATE '2025-04-01', 'Ana'),
    ('Teclado Mecânico', 'Acessórios', 300.00, DATE '2025-04-02', 'Carlos'),
    ('Monitor 24"', 'Eletrônicos', 1200.00, DATE '2025-04-02', 'Bruna'),
    ('Fone Bluetooth', 'Acessórios', 200.00, DATE '2025-04-03', 'Ana'),
    ('Notebook HP', 'Eletrônicos', 4000.00, DATE '2025-04-03', 'Carlos'),
    ('Webcam HD', 'Acessórios', 180.00, DATE '2025-04-04', 'Bruna'),
    ('Carregador Portátil', 'Acessórios', 120.00, DATE '2025-04-04', 'Ana'),
    ('SSD 1TB', 'Componentes', 500.00, DATE '2025-04-05', 'Carlos'),
    ('Cabo HDMI', 'Acessórios', 50.00, DATE '2025-04-05', 'Bruna');

DROP TABLE CLIENTES;
CREATE TABLE IF NOT EXISTS CLIENTES (
    ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    NOME VARCHAR(100),
    CIDADE VARCHAR(50),
    ESTADO VARCHAR(2)

);

INSERT INTO CLIENTES(NOME,CIDADE,ESTADO) VALUES
('Maddie', 'São Paulo', 'SP'),
('Felipe', 'Macapá', 'AP'),
('Samuel', 'Porto Velho', 'RO');

ALTER TABLE VENDAS ADD ID_CLIENTE NUMBER;
ALTER TABLE VENDAS ADD CONSTRAINT FK_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID);

UPDATE VENDAS
SET ID_CLIENTE = CASE VENDEDOR
    WHEN 'Carlos' THEN 1
    WHEN 'Ana' THEN 2
    WHEN 'Bruna' THEN 3
END;

SELECT PRODUTO, ID_CLIENTE FROM VENDAS;


-- Liste o nome do cliente e o produto de cada venda, mostrando também a cidade.
SELECT
    v.produto,
    c.nome AS cliente,
    c.cidade
FROM VENDAS v
INNER JOIN CLIENTES c
    ON v.id_cliente = c.id;

-- Mostre o total de vendas por estado.
SELECT
    COUNT(v.DATA_VENDA) AS QTD_VENDAS,
    c.ESTADO
FROM VENDAS v
INNER JOIN CLIENTES c
    ON c.id = v.id_CLIENTE
GROUP BY c.ESTADO;

-- Quais cidades tiveram mais de R$ 2.000,00 em vendas no total?
SELECT
    SUM(v.VALOR) AS VALOR_VENDIDO,
    c.CIDADE
FROM VENDAS v
INNER JOIN CLIENTES c
    ON c.id = v.id
GROUP BY c.CIDADE
