-- 1. Criação da tabela de vendas
DROP TABLE VENDAS PURGE;

CREATE TABLE VENDAS (
    id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    produto       VARCHAR2(100) NOT NULL,
    categoria     VARCHAR2(50)  NOT NULL,
    valor         NUMBER(10,2)  NOT NULL CHECK (valor > 0),
    data_venda    DATE          DEFAULT SYSDATE,
    vendedor      VARCHAR2(100) NOT NULL
);

-- 2. Inserção de 30 registros reais e variados
INSERT INTO VENDAS (produto, categoria, valor, data_venda, vendedor) VALUES
    ('Notebook Dell Inspiron', 'Eletrônicos', 4500.00, DATE '2025-04-01', 'Carlos'),
    ('Mouse Gamer RGB', 'Acessórios', 150.00, DATE '2025-04-01', 'Ana'),
    ('Teclado Mecânico Blue', 'Acessórios', 300.00, DATE '2025-04-02', 'Carlos'),
    ('Monitor 24" Full HD', 'Eletrônicos', 1200.00, DATE '2025-04-02', 'Bruna'),
    ('Fone Bluetooth Premium', 'Acessórios', 200.00, DATE '2025-04-03', 'Ana'),
    ('Notebook HP Pavilion', 'Eletrônicos', 4000.00, DATE '2025-04-03', 'Carlos'),
    ('Webcam Full HD 1080p', 'Acessórios', 180.00, DATE '2025-04-04', 'Bruna'),
    ('Carregador Portátil 20000mAh', 'Acessórios', 120.00, DATE '2025-04-04', 'Ana'),
    ('SSD 1TB NVMe', 'Componentes', 500.00, DATE '2025-04-05', 'Carlos'),
    ('Cabo HDMI 2.1 2m', 'Acessórios', 50.00, DATE '2025-04-05', 'Bruna'),
    ('Smartphone Galaxy S24', 'Eletrônicos', 5200.00, DATE '2025-04-06', 'Diego'),
    ('Capa para Galaxy S24', 'Acessórios', 80.00, DATE '2025-04-06', 'Ana'),
    ('Carregador Turbo 65W', 'Acessórios', 130.00, DATE '2025-04-07', 'Diego'),
    ('HD Externo 2TB', 'Componentes', 420.00, DATE '2025-04-07', 'Bruna'),
    ('Mousepad Gamer XL', 'Acessórios', 70.00, DATE '2025-04-08', 'Ana'),
    ('Notebook Lenovo IdeaPad', 'Eletrônicos', 3800.00, DATE '2025-04-08', 'Carlos'),
    ('Adaptador USB-C para HDMI', 'Acessórios', 90.00, DATE '2025-04-09', 'Diego'),
    ('Memória RAM 16GB DDR4', 'Componentes', 350.00, DATE '2025-04-09', 'Bruna'),
    ('Cooler para Notebook', 'Acessórios', 60.00, DATE '2025-04-10', 'Ana'),
    ('Roteador Wi-Fi 6', 'Eletrônicos', 700.00, DATE '2025-04-10', 'Carlos'),
    ('Fonte 750W 80 Plus Gold', 'Componentes', 650.00, DATE '2025-04-11', 'Diego'),
    ('Gabinete Gamer RGB', 'Componentes', 400.00, DATE '2025-04-11', 'Bruna'),
    ('Fone de Ouvido Studio', 'Acessórios', 800.00, DATE '2025-04-12', 'Ana'),
    ('Tablet Samsung Galaxy Tab', 'Eletrônicos', 2200.00, DATE '2025-04-12', 'Carlos'),
    ('Suporte para Notebook', 'Acessórios', 110.00, DATE '2025-04-13', 'Diego'),
    ('Placa de Vídeo RTX 4060', 'Componentes', 3200.00, DATE '2025-04-13', 'Bruna'),
    ('Microfone Gamer Condensador', 'Acessórios', 250.00, DATE '2025-04-14', 'Ana'),
    ('Processador Intel i7-13700K', 'Componentes', 2800.00, DATE '2025-04-14', 'Carlos'),
    ('Caixa de Som Bluetooth', 'Acessórios', 300.00, DATE '2025-04-15', 'Diego'),
    ('Smartwatch Amazfit GTS 4', 'Eletrônicos', 900.00, DATE '2025-04-15', 'Bruna');


--- Liste os 3 produtos com os maiores valores de venda. Mostre
--- Nome do produto
--- Valor
--- Categoria.

SELECT
    PRODUTO,
    COUNT(*) AS QTD_VENDAS,
    SUM(VALOR) AS VALOR_TOTAL,
    CATEGORIA
FROM VENDAS
GROUP BY PRODUTO, CATEGORIA
ORDER BY VALOR_TOTAL DESC
FETCH FIRST 3 ROWS ONLY;

--- Mostre, para cada vendedor:
--- Nome do vendedor
--- Quantidade total de vendas realizadas
--- Valor total vendido (soma dos valores)
--- Ordene pelo valor total vendido, do maior para o menor.

SELECT
    VENDEDOR,
    COUNT(VENDEDOR) AS QTD_VENDAS,
    SUM(VALOR) AS VALOR_TOTAL
FROM VENDAS
GROUP BY VENDEDOR
ORDER BY VALOR_TOTAL DESC;

--- Mostre o total vendido **por dia**, em ordem cronológica.
--- Colunas: Data da venda, total vendido naquele dia

SELECT 
    DATA_VENDA AS DIA_DA_VENDA,
    COUNT(DATA_VENDA) AS QTD_DIA,
    SUM (VALOR) AS VALOR_TOTAL_DIA
FROM VENDAS
GROUP BY DATA_VENDA
ORDER BY DATA_VENDA ASC;

--- Liste os produtos que custam **menos de R$200** e que foram vendidos
--- **mais de uma vez**.
--- Mostre: nome do produto, valor unitário e quantas vezes foi vendido.

SELECT
    PRODUTO,
    COUNT(PRODUTO) AS QTD_VENDIDA,
    VALOR AS PRECO_UNITARIO
FROM VENDAS
WHERE VALOR < 200
GROUP BY PRODUTO, VALOR
HAVING COUNT(PRODUTO) > 1
ORDER BY QTD_VENDIDA DESC;

--- Para **cada categoria**, mostre qual vendedor teve o **maior valor total vendido** nela.
--- Colunas esperadas: Categoria, Vendedor Campeão, Valor Total Vendido por ele na categoria.

SELECT 
    CATEGORIA,
    VENDEDOR AS VENDEDOR_CAMPEAO,
    SUM(VALOR) AS VALOR_VENDIDO,
    DENSE_RANK() OVER (PARTITION BY CATEGORIA ORDER BY SUM(VALOR) DESC) AS RANKING 
FROM VENDAS
GROUP BY VENDEDOR, CATEGORIA
ORDER BY RANKING ASC
FETCH FIRST 3 ROWS ONLY;