CREATE TABLE VENDAS (
    id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    produto       VARCHAR2(100) NOT NULL,
    categoria     VARCHAR2(50)  NOT NULL,
    valor         NUMBER(10,2)  NOT NULL CHECK (valor > 0),
    data_venda    DATE          DEFAULT SYSDATE,
    vendedor      VARCHAR2(100) NOT NULL
);

INSERT INTO VENDAS (produto, categoria, valor, data_venda, vendedor) 
VALUES 
    ('Notebook Dell', 'Eletrônicos', 4500.00, DATE '2025-04-01', 'Carlos'),
    ('Mouse Gamer', 'Acessórios', 150.00, DATE '2025-04-01', 'Ana'),
    ('Teclado Mecânico', 'Acessórios', 300.00, DATE '2025-04-02', 'Carlos'),
    ('Monitor 24"', 'Eletrônicos', 1200.00, DATE '2025-04-02', 'Bruna'),
    ('Fone Bluetooth', 'Acessórios', 200.00, DATE '2025-04-03', 'Ana'),
    ('Notebook HP', 'Eletrônicos', 4000.00, DATE '2025-04-03', 'Carlos'),
    ('Webcam HD', 'Acessórios', 180.00, DATE '2025-04-04', 'Bruna'),
    ('Carregador Portátil', 'Acessórios', 120.00, DATE '2025-04-04', 'Ana'),
    ('SSD 1TB', 'Componentes', 500.00, DATE '2025-04-05', 'Carlos'),
    ('Cabo HDMI', 'Acessórios', 50.00, DATE '2025-04-05', 'Bruna');


    --- Liste todos os produtos vendidos por “Ana”, ordenados por data.
SELECT PRODUTO, VENDEDOR, DATA_VENDA
FROM VENDAS
WHERE VENDEDOR = 'Ana'
ORDER BY DATA_VENDA DESC;


    --- Mostre o valor total vendido na categoria “Eletrônicos”.
SELECT
    categoria,
    SUM(VALOR) AS VALOR_TOTAL
FROM VENDAS
WHERE CATEGORIA = 'Eletrônicos'
GROUP BY CATEGORIA;


--- Quais produtos custam entre R$200 e R$1000? Mostre nome e valor.
SELECT PRODUTO, VALOR
FROM VENDAS
WHERE VALOR >= 200 AND VALOR <= 1000
ORDER BY VALOR ASC;

---Mostre quantas vendas cada vendedor realizou e o valor total vendido por ele, ordenado do maior para o menor faturamento.
SELECT
    VENDEDOR,
    COUNT(*) AS QTD_VENDAS,
    SUM(VALOR) AS VALOR_TOTAL
FROM VENDAS
GROUP BY VENDEDOR
ORDER BY VALOR_TOTAL DESC;