-- Relação de atendimentos com dados de paciente, médico e leito
SELECT 
    A.ID_ATENDIMENTO,
    P.NOME AS PACIENTE,
    M.ESPECIALIDADE AS MEDICO,
    L.ID_LEITO,
    S.NOME_SETOR,
    A.DIAGNOSTICO
FROM ATENDIMENTO A
JOIN PACIENTE P ON A.ID_PACIENTE = P.ID_PACIENTE
JOIN MEDICO M ON A.ID_MEDICO = M.ID_MEDICO
LEFT JOIN LEITO L ON A.ID_LEITO = L.ID_LEITO
LEFT JOIN SETOR S ON L.ID_SETOR = S.ID_SETOR;

-- Total de atendimentos por setor
SELECT 
    S.NOME_SETOR,
    COUNT(*) AS TOTAL_ATENDIMENTOS
FROM ATENDIMENTO A
JOIN LEITO L ON A.ID_LEITO = L.ID_LEITO
JOIN SETOR S ON L.ID_SETOR = S.ID_SETOR
GROUP BY S.NOME_SETOR
HAVING COUNT(*) > 0;

-- Pacientes com mais de um atendimento
SELECT 
    P.NOME,
    COUNT(A.ID_ATENDIMENTO) AS QTD_ATENDIMENTOS
FROM PACIENTE P
JOIN ATENDIMENTO A ON A.ID_PACIENTE = P.ID_PACIENTE
GROUP BY P.NOME
HAVING COUNT(A.ID_ATENDIMENTO) > 1;

-- Leitos ocupados por setor
SELECT 
    L.ID_LEITO,
    L.STATUS_LEITO,
    S.NOME_SETOR
FROM LEITO L
JOIN SETOR S ON L.ID_SETOR = S.ID_SETOR
WHERE L.STATUS_LEITO = 'OCUPADO';

-- Total recebido por tipo de pagamento
SELECT 
    TIPO_PAGAMENTO,
    SUM(VALOR) AS TOTAL
FROM FINANCEIRO
GROUP BY TIPO_PAGAMENTO;

SELECT 
    P.ID_PACIENTE,
    P.NOME
FROM PACIENTE P
WHERE NOT EXISTS (
    SELECT 1
    FROM ATENDIMENTO A
    WHERE A.ID_PACIENTE = P.ID_PACIENTE
);