-------------------------------------------------------------
-- TABELA: SETOR
-- Armazena os setores do hospital (ex.: Emergência, UTI, Pediatria)
-------------------------------------------------------------

CREATE TABLE SETOR (
    ID_SETOR NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, -- Identificador único do setor
    NOME_SETOR VARCHAR2(200) NOT NULL, -- Nome do setor
    BLOCO VARCHAR2(200), -- Bloco físico do hospital onde o setor está localizado
    TIPO_SETOR VARCHAR2(200) -- Classificação do setor (Atendimento, Internação etc.)
);

-------------------------------------------------------------
-- TABELA: PACIENTE
-- Contém os dados cadastrais dos pacientes do hospital
-------------------------------------------------------------

CREATE TABLE PACIENTE (
    ID_PACIENTE NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, -- Identificador do paciente
    NOME        VARCHAR2(200) NOT NULL, -- Nome completo do paciente
    CPF         NUMBER UNIQUE NOT NULL, -- CPF único para evitar duplicidades
    PLANO       VARCHAR2(200) -- Plano de saúde
);

-------------------------------------------------------------
-- TABELA: MEDICO
-- Dados dos médicos que atendem no hospital
-------------------------------------------------------------

CREATE TABLE MEDICO (
    ID_MEDICO NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, -- Identificador do médico
    CRM       NUMBER UNIQUE NOT NULL, -- Número do CRM (único)
    ESPECIALIDADE VARCHAR2(200) -- Especialidade médica (ex.: Cardiologia, Clínico Geral)
);

-------------------------------------------------------------
-- TABELA: ENFERMEIRO
-- Registra as informações de cada enfermeiro e seu setor
-------------------------------------------------------------

CREATE TABLE ENFERMEIRO (
    ID_ENFERMEIRO NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, -- Identificador do enfermeiro
    NOME          VARCHAR2(200) NOT NULL,
    COREN         NUMBER UNIQUE NOT NULL,
    ID_SETOR      NUMBER,
    FOREIGN KEY (ID_SETOR) REFERENCES SETOR(ID_SETOR) -- Relacionamento com SETOR
);

-------------------------------------------------------------
-- TABELA: LEITO
-- Representa os leitos disponíveis dentro de um setor
-------------------------------------------------------------

CREATE TABLE LEITO (
    ID_LEITO NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, -- Identificador do leito
    STATUS_LEITO VARCHAR2(200), -- Situação atual do leito (LIVRE ou OCUPADO)
    ID_SETOR NUMBER NOT NULL, -- Setor ao qual o leito pertence
    FOREIGN KEY (ID_SETOR) REFERENCES SETOR(ID_SETOR)
);

-------------------------------------------------------------
-- TABELA: EXAME
-- Catálogo de exames realizados pelo hospital
-------------------------------------------------------------

CREATE TABLE EXAME (
    ID_EXAME NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, -- Identificador do exame
    NOME VARCHAR2(200) NOT NULL,
    TIPO_EXAME VARCHAR2(200) NOT NULL, -- Tipo (Laboratório, Imagem, etc.)
    DESCRICAO VARCHAR2(200)
);

-------------------------------------------------------------
-- TABELA: ATENDIMENTO
-- Registro principal de atendimentos realizados no hospital
-------------------------------------------------------------

CREATE TABLE ATENDIMENTO (
    ID_ATENDIMENTO NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    AGENDAMENTO    VARCHAR2(200),
    DIAGNOSTICO    VARCHAR2(200),
    OBSERVACOES    VARCHAR2(200), -- Observações complementares

    ID_PACIENTE NUMBER NOT NULL, -- Paciente atendido
    ID_MEDICO   NUMBER NOT NULL, -- Médico responsável
    ID_LEITO    NUMBER, -- Leito utilizado (se houver)

    FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID_PACIENTE),
    FOREIGN KEY (ID_MEDICO) REFERENCES MEDICO(ID_MEDICO),
    FOREIGN KEY (ID_LEITO) REFERENCES LEITO(ID_LEITO)
);

-------------------------------------------------------------
-- TABELA ASSOCIATIVA: ATENDIMENTO_EXAME
-- Relaciona quais exames foram solicitados em cada atendimento
-- Representa uma relação N:N entre ATENDIMENTO e EXAME
-------------------------------------------------------------

CREATE TABLE ATENDIMENTO_EXAME (
    ID_ATENDIMENTO_EXAME NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    DATA_SOLICITACAO DATE NOT NULL,

    ID_ATENDIMENTO NUMBER NOT NULL,
    ID_EXAME       NUMBER NOT NULL,

    FOREIGN KEY (ID_ATENDIMENTO) REFERENCES ATENDIMENTO(ID_ATENDIMENTO),
    FOREIGN KEY (ID_EXAME) REFERENCES EXAME(ID_EXAME)
);

-------------------------------------------------------------
-- TABELA ASSOCIATIVA: ATENDIMENTO_ENFERMEIRO
-- Registra quais enfermeiros participaram de determinado atendimento
-- Relação N:N entre ATENDIMENTO e ENFERMEIRO
-------------------------------------------------------------

CREATE TABLE ATENDIMENTO_ENFERMEIRO (
    ID_ATENDIMENTO_ENFERMEIRO NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,

    ID_ATENDIMENTO NUMBER NOT NULL,
    ID_ENFERMEIRO  NUMBER NOT NULL,

    FOREIGN KEY (ID_ATENDIMENTO) REFERENCES ATENDIMENTO(ID_ATENDIMENTO),
    FOREIGN KEY (ID_ENFERMEIRO)  REFERENCES ENFERMEIRO(ID_ENFERMEIRO)
);

-------------------------------------------------------------
-- TABELA: FINANCEIRO
-- Armazena informações de cobrança relacionadas ao atendimento
-------------------------------------------------------------

CREATE TABLE FINANCEIRO (
    ID_FINANCEIRO NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY, -- Identificador do registro financeiro
    ID_ATENDIMENTO NUMBER NOT NULL,
    VALOR NUMBER(10,2) NOT NULL, -- Valor cobrado
    TIPO_PAGAMENTO VARCHAR2(200), -- Forma de pagamento (PIX, Cartão, Convênio, etc.)

    FOREIGN KEY (ID_ATENDIMENTO) REFERENCES ATENDIMENTO(ID_ATENDIMENTO)
);