CREATE TABLE VENDAS (
    id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    produto       VARCHAR2(100) NOT NULL,
    categoria     VARCHAR2(50)  NOT NULL,
    valor         NUMBER(10,2)  NOT NULL CHECK (valor > 0),
    data_venda    DATE          DEFAULT SYSDATE,
    vendedor      VARCHAR2(100) NOT NULL
);

-- 2. Inserção de 30 registros reais e variados
INSERT INTO VENDAS (produto, categoria, valor, data_venda, vendedor) VALUES
    ('Notebook Dell Inspiron', 'Eletrônicos', 4500.00, DATE '2025-04-01', 'Carlos'),
    ('Mouse Gamer RGB', 'Acessórios', 150.00, DATE '2025-04-01', 'Ana'),
    ('Teclado Mecânico Blue', 'Acessórios', 300.00, DATE '2025-04-02', 'Carlos'),
    ('Monitor 24" Full HD', 'Eletrônicos', 1200.00, DATE '2025-04-02', 'Bruna'),
    ('Fone Bluetooth Premium', 'Acessórios', 200.00, DATE '2025-04-03', 'Ana'),
    ('Notebook HP Pavilion', 'Eletrônicos', 4000.00, DATE '2025-04-03', 'Carlos'),
    ('Webcam Full HD 1080p', 'Acessórios', 180.00, DATE '2025-04-04', 'Bruna'),
    ('Carregador Portátil 20000mAh', 'Acessórios', 120.00, DATE '2025-04-04', 'Ana'),
    ('SSD 1TB NVMe', 'Componentes', 500.00, DATE '2025-04-05', 'Carlos'),
    ('Cabo HDMI 2.1 2m', 'Acessórios', 50.00, DATE '2025-04-05', 'Bruna'),
    ('Smartphone Galaxy S24', 'Eletrônicos', 5200.00, DATE '2025-04-06', 'Diego'),
    ('Capa para Galaxy S24', 'Acessórios', 80.00, DATE '2025-04-06', 'Ana'),
    ('Carregador Turbo 65W', 'Acessórios', 130.00, DATE '2025-04-07', 'Diego'),
    ('HD Externo 2TB', 'Componentes', 420.00, DATE '2025-04-07', 'Bruna'),
    ('Mousepad Gamer XL', 'Acessórios', 70.00, DATE '2025-04-08', 'Ana'),
    ('Notebook Lenovo IdeaPad', 'Eletrônicos', 3800.00, DATE '2025-04-08', 'Carlos'),
    ('Adaptador USB-C para HDMI', 'Acessórios', 90.00, DATE '2025-04-09', 'Diego'),
    ('Memória RAM 16GB DDR4', 'Componentes', 350.00, DATE '2025-04-09', 'Bruna'),
    ('Cooler para Notebook', 'Acessórios', 60.00, DATE '2025-04-10', 'Ana'),
    ('Roteador Wi-Fi 6', 'Eletrônicos', 700.00, DATE '2025-04-10', 'Carlos'),
    ('Fonte 750W 80 Plus Gold', 'Componentes', 650.00, DATE '2025-04-11', 'Diego'),
    ('Gabinete Gamer RGB', 'Componentes', 400.00, DATE '2025-04-11', 'Bruna'),
    ('Fone de Ouvido Studio', 'Acessórios', 800.00, DATE '2025-04-12', 'Ana'),
    ('Tablet Samsung Galaxy Tab', 'Eletrônicos', 2200.00, DATE '2025-04-12', 'Carlos'),
    ('Suporte para Notebook', 'Acessórios', 110.00, DATE '2025-04-13', 'Diego'),
    ('Placa de Vídeo RTX 4060', 'Componentes', 3200.00, DATE '2025-04-13', 'Bruna'),
    ('Microfone Gamer Condensador', 'Acessórios', 250.00, DATE '2025-04-14', 'Ana'),
    ('Processador Intel i7-13700K', 'Componentes', 2800.00, DATE '2025-04-14', 'Carlos'),
    ('Caixa de Som Bluetooth', 'Acessórios', 300.00, DATE '2025-04-15', 'Diego'),
    ('Smartwatch Amazfit GTS 4', 'Eletrônicos', 900.00, DATE '2025-04-15', 'Bruna');



--- Liste todos os produtos mais caros do que o produto mais barato da categoria "Eletrônicos".
    SELECT PRODUTO, VALOR, CATEGORIA, (SELECT MIN(VALOR) FROM VENDAS WHERE CATEGORIA = 'Eletrônicos') AS VALOR_MIN
FROM VENDAS
WHERE VALOR > (
        SELECT MIN(VALOR)
        FROM VENDAS
        WHERE CATEGORIA = 'Eletrônicos'
) AND CATEGORIA = 'Eletrônicos'
ORDER BY VALOR DESC;



--- Mostre o vendedor que realizou a maior venda registrada na tabela.
SELECT VENDEDOR, PRODUTO, VALOR
FROM VENDAS
WHERE VALOR = (
    SELECT MAX(VALOR)
    FROM VENDAS);



--- Liste as categorias que têm pelo menos um produto acima do preço médio geral.
SELECT PRODUTO, CATEGORIA, VALOR, (SELECT AVG(VALOR) FROM VENDAS) AS VALOR_MED
FROM VENDAS
WHERE VALOR > (
    SELECT AVG(VALOR)
    FROM VENDAS
);



--- Monte um ranking dos 3 produtos mais caros vendidos por cada vendedor.
SELECT *
FROM(
    SELECT
    PRODUTO,
    VENDEDOR,
    VALOR,
    DENSE_RANK() OVER (PARTITION BY VENDEDOR ORDER BY VALOR DESC) AS RANKING
    FROM VENDAS) t
WHERE t.RANKING < 4  
ORDER BY VENDEDOR;
